version: "3.7"

networks:
  shared:

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:${LOCALSTACK_VERSION:-3.0.2}
    platform: linux/${DOCKER_PLATFORM:-amd64}
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      DEBUG: "true"
      LAMBDA_DOCKER_NETWORK: shared
      MAIN_DOCKER_NETWORK: shared
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - shared
