version: "3.7"

volumes:
  code_dir_tmp:

services:
  tfcoding:
    container_name: tfcoding
    image: ${DOCKER_TAG:-unfor19/tfcoding:latest}
    volumes:
      - ./:/src/:ro
      - code_dir_tmp:/tmp/
    command:
      - "--src_dir_relative_path"
      - "${SRC_DIR_RELATIVE_PATH:-examples/basic}"
      - "--watching"
    restart: always
    tty: true # colorful output
