version: "3.9"

networks:
  shared:
    name: shared

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:${LOCALSTACK_VERSION:-3.0.2}
    platform: linux/${DOCKER_PLATFORM:-amd64}
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      DEBUG: "true"
      LAMBDA_DOCKER_NETWORK: shared
      MAIN_DOCKER_NETWORK: shared
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - shared

  tfcoding-aws:
    container_name: tfcoding-aws
    platform: linux/${DOCKER_PLATFORM:-amd64}
    image: ${DOCKER_TAG_LATEST:-unfor19/tfcoding:latest}
    volumes:
      - ./:/src/:ro
      - ${HOME}/.aws:/home/appuser/.aws:ro
    environment:
      AWS_REGION: "us-east-1"
      AWS_DEFAULT_REGION: "us-east-1"
    command:
      - "--src_dir_relative_path"
      - "${SRC_DIR_RELATIVE_PATH:-examples/mock-aws}"
      - "--watching"
      - "--mock_aws"
    restart: always
    tty: true # colorful output
    networks:
      - shared
