apiVersion: v1
kind: Secret
metadata:
  name: stakater-helm-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://stakater.github.io/stakater-charts
  name: stakater-helm-repo
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: tfcoding-git-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/unfor19/tfcoding.git
  name: tfcoding-git-repo
  type: git
