name: Push latest version to DockerHub

on:
  push:
    paths-ignore:
      - "README.md"
    # TODO: Remove
    branches-ignore:
      - "feature/kubernetes"

env:
  TARGET_APP: app
  DOCKERHUB_REPOSITORY: docker.io/unfor19/tfcoding
  TFCODING_VERSION: 0.0.12

jobs:
  build-push:
    name: Docker Build Push
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.4.6"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.5.5"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.6.6"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.7.0-rc1"
    env:
      DOCKERFILE_PATH: ${{ matrix.DOCKERFILE_PATH }}
      TERRAFORM_VERSION: ${{ matrix.TERRAFORM_VERSION }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build - amd64 for running Test
        uses: docker/build-push-action@v5.1.0
        with:
          file: Dockerfile
          context: .
          push: false
          platforms: linux/amd64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.GITHUB_REF_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: true # For later to run tests on the built image
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: make test
      - name: Side Branch - Build - arm64, Push - arm64,amd64
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v5.1.0
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.TERRAFORM_VERSION }}-${{ env.GITHUB_REF_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.TERRAFORM_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Latest master - Build - arm64, Push - arm64,amd64
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5.1.0
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.TERRAFORM_VERSION }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.TERRAFORM_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Latest Tag - Build - arm64, Push - arm64,amd64
        if: github.ref == 'refs/heads/master' && env.TERRAFORM_VERSION == '1.6.6'
        uses: docker/build-push-action@v5.1.0
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:latest
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.TERRAFORM_VERSION }}
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
