name: Push latest version to DockerHub

on:
  push:
    paths-ignore:
      - "README.md"

env:
  TARGET_APP: app
  DOCKERHUB_REPOSITORY: docker.io/unfor19/tfcoding
  TFCODING_VERSION: 0.0.9

jobs:
  build-push:
    name: Docker Build Push
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.13.6"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.14.8"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.15.0-beta2"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.0.6"
          - DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.2.9"
    env:
      DOCKERFILE_PATH: ${{ matrix.DOCKERFILE_PATH }}
      TERRAFORM_VERSION: ${{ matrix.TERRAFORM_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.DOCKER_WORKDIR }}
          push: false
          platforms: linux/amd64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.GITHUB_REF_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: true # For later to run tests on the built image
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: make test
      - name: Docker Build amd64 and load
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.DOCKER_WORKDIR }}
          push: true
          platforms: linux/amd64,linux/arm64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.GITHUB_REF_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Build arm64 and Push
        if: ${{ env.GITHUB_REF_SLUG == 'master' }}
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.DOCKER_WORKDIR }}
          push: true
          platforms: linux/amd64,linux/arm64
          target: app
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TFCODING_VERSION }}-latest
            ${{ env.DOCKERHUB_REPOSITORY }}:latest
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
