name: Push latest version to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"

env:
  TARGET_BASE: download
  TARGET_APP: app
  DOCKER_BUILDKIT: 1

jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.12.30"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.12.30"
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.13.6"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.13.6"
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.14.8"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.14.8"
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.15.0-beta2"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.15.0-beta2"
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:1.0.6"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.0.6"
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set env vars
        run: |
          export TERRAFORM_VERSION="${{ matrix.TERRAFORM_VERSION }}"
          echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}" >> $GITHUB_ENV
      - name: docker login ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: docker pull cached
        run: |
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}" || true
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}" || true
      - name: docker build cached
        run: |
          docker build . -t "cached-${TARGET_BASE}" \
            --cache-from="${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}" \
            -f "${{ matrix.DOCKERFILE_PATH }}" \
            --target "${TARGET_BASE}" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg TERRAFORM_VERSION="$TERRAFORM_VERSION"
          docker build . -t "cached-${TARGET_APP}" \
            --cache-from="${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}" \
            -f "${{ matrix.DOCKERFILE_PATH }}" \
            --target "${TARGET_APP}" \
            --build-arg BUILDKIT_INLINE_CACHE=1
      - name: docker tag cached
        run: |
          docker tag "cached-${TARGET_BASE}" "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}"
          docker tag "cached-${TARGET_APP}"  "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"
      - name: docker push cached to ghcr
        env:
          GITHUB_TOKEN: "${{ secrets.GHTOKEN_PUSH_PKG }}"
        run: |
          docker push "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}"
          docker push "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"

  dockerhub-push:
    needs: docker-build
    name: docker push
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # 0.12.30-latest
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.12.30"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.12.30"
            DOCKERHUB_TAG_PREFIX: "unfor19/tfcoding:0.12.30-latest"
          # 0.13.6-latest
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.13.6"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.13.6"
            DOCKERHUB_TAG_PREFIX: "unfor19/tfcoding:0.13.6-latest"
          # latest (TERRAFORM_VERSION=0.13.6)
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.13.6"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.13.6"
            DOCKERHUB_TAG_PREFIX: "unfor19/tfcoding:latest"
          # 0.14.8-latest
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.14.8"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.14.8"
            DOCKERHUB_TAG_PREFIX: "unfor19/tfcoding:0.14.8-latest"
          # 0.15.0-beta2
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:0.15.0-beta2"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "0.15.0-beta2"
            DOCKERHUB_TAG_PREFIX: "unfor19/tfcoding:0.15.0-beta2"
          # 1.0.6
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/tfcoding:1.0.6"
            DOCKERFILE_PATH: Dockerfile
            TERRAFORM_VERSION: "1.0.6"     
            DOCKERHUB_TAG_PREFIX: "unfor19/tfcoding:1.0.6"
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set env vars
        run: |
          export DOCKERHUB_TAG="${{ matrix.DOCKERHUB_TAG_PREFIX }}"
          echo "DOCKERHUB_TAG=${DOCKERHUB_TAG}" >> $GITHUB_ENV
          export TERRAFORM_VERSION="${{ matrix.TERRAFORM_VERSION }}"
          echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}" >> $GITHUB_ENV
      - name: docker pull cached from ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"
      - name: docker tag image
        run: |
          docker tag "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}" "$DOCKERHUB_TAG"
      - name: test docker image
        run: |
          ./scripts/tests.sh
      - name: docker push to dockerhub
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "$DOCKERHUB_TAG"
