name: Push latest version to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"

env:
  DOCKER_TAG: unfor19/tfcoding:latest

jobs:
  dockerhub-latest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag "${DOCKER_TAG}"
      - name: Test Docker Image
        run: |
          ./scripts/tests.sh
      - name: Push to DockerHub
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}" && echo "Pushed $DOCKER_TAG"
